### ISSUE TITLE
Add bulder that matches url by regular expression patterns

### ISSUE THREAD

**Issue by Paca-Vaca** [Artezio/ArtBreadcrumbsBundle#2]
What I want to do is to create another builder, that would get the scheme of breadcrumbs that would looks like this:

```
label: "breadcrumbs.home"
regexp: ^{home}$
children:
      editUser:
         label: "breadcrumbs.admin_user_edit"
         regexp: ^{user}/(\d+)$
         previous_url: /users
      createUser:
         label: "breadcrumbs.admin_user_create"
         regexp: ^{user/new}$
         previous_url: /users
      listUser:
         label: "breadcrumbs.admin_user_list"
         regexp: ^{users}$
         previous_url: /
```

The main idea is - that a developer can write all structure of breadcrumbs by hands

What do you thinks about this? Does it worth it?)
